name: "Rapportage sportmoment"
description: "Vul dit formulier in na een sportmoment."
title: "[Rapportage] Rapportage"
labels: [rapportage]
body:
  - type: input
    id: datum
    attributes:
      label: Datum
      description: "JJJJ-MM-DD"
      placeholder: "2025-08-16"
    validations: { required: true }
  - type: input
    id: tijdvak
    attributes:
      label: Tijd
      placeholder: "14:00–15:00"
    validations: { required: true }
  - type: input
    id: groep
    attributes:
      label: Groep
      placeholder: "Bijv. Groep A / Unit 3"
    validations: { required: true }
  - type: input
    id: begeleider
    attributes:
      label: Begeleider
      placeholder: "Voor- en achternaam"
    validations: { required: true }
  - type: dropdown
    id: activiteit
    attributes:
      label: Activiteit
      options: [Voetbal, Fitness, Basketbal, Boksen, Hardlopen, Anders]
    validations: { required: true }
  - type: textarea
    id: opkomst
    attributes:
      label: Opkomst
      description: "Aanwezig/afwezig + aantallen"
  - type: textarea
    id: inhoud
    attributes:
      label: Inhoud & verloop
  - type: textarea
    id: bijzonderheden
    attributes:
      label: Bijzonderheden / incidenten
  - type: textarea
    id: vervolg
    attributes:
      label: Vervolgacties
