name: Label test
on:
  issues:
    types: [opened, edited]
permissions:
  issues: write
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const name = "rapportage";
            try { await github.rest.issues.getLabel({ owner: context.repo.owner, repo: context.repo.repo, name }); }
            catch (_) { await github.rest.issues.createLabel({ owner: context.repo.owner, repo: context.repo.repo, name, color: "FF7A00" }); }
            await github.rest.issues.addLabels({
              owner: context.repo.owner, repo: context.repo.repo,
              issue_number: context.payload.issue.number, labels: [name]
            });
