name: Build rapportage JSON
on:
  issues:
    types: [opened, edited]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Workflow werkt!"
