name: Build rapportage JSON
on:
  issues:
    types: [opened, edited, labeled, unlabeled]
  workflow_dispatch:
permissions:
  contents: write
  issues: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ensure 'rapportage' label exists
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.issues.getLabel({ owner: context.repo.owner, repo: context.repo.repo, name: "rapportage" });
              core.info("Label 'rapportage' exists");
            } catch (e) {
              await github.rest.issues.createLabel({
                owner: context.repo.owner, repo: context.repo.repo,
                name: "rapportage", color: "FF7A00",
                description: "Ingevulde sport-rapportage"
              });
              core.info("Label 'rapportage' created");
            }

      - name: Retitle issue from form fields
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue?.body || "";
            function pick(label) {
              const re = new RegExp(String.raw`\\*\\*${label}\\*\\*[\\r\\n]+([\\s\\S]*?)(?=(\\*\\*.+?\\*\\*)|$)`, "g");
              const m = re.exec(body);
              return m ? m[1].trim() : "";
            }
            const groep = pick("Groep") || "—";
            const datum = pick("Datum") || "—";
            const begeleider = pick("Begeleider") || "—";
            const newTitle = `[Rapportage] ${groep} — ${datum} — ${begeleider}`;
            if ((context.payload.issue.title || "") !== newTitle) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                title: newTitle
              });
              core.info(`Title updated to: ${newTitle}`);
            } else {
              core.info("Title already correct, skipping.");
            }

      - name: Build JSON (no deps)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: node scripts/build.mjs

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.json || true
          git commit -m "chore: update rapportage JSON" || echo "No changes"
          git push || true
